# Ruta 1: FichaVet
spring.cloud.gateway.routes[0].id=ms-fichavet
spring.cloud.gateway.routes[0].uri=lb://ms-fichavet
spring.cloud.gateway.routes[0].predicates[0]=Path=/fichas/**

# Ruta 2: Refugios
spring.cloud.gateway.routes[1].id=ms-refugios
spring.cloud.gateway.routes[1].uri=lb://ms-refugios
spring.cloud.gateway.routes[1].predicates[0]=Path=/refugios/**

# Ruta 3: Mascotas
spring.cloud.gateway.routes[2].id=ms-mascotas
spring.cloud.gateway.routes[2].uri=lb://ms-mascotas
spring.cloud.gateway.routes[2].predicates[0]=Path=/mascotas/**