spring.application.name=eureka-server
server.port=8761

# Estas dos líneas son obligatorias para que no se busque a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Para que sea más rápido ver quién está conectado en desarrollo
eureka.server.wait-time-in-ms-when-sync-empty=0